baseurl = "https://e-lle-phant.com/"
languageCode = "en-us"
title = "Training the Next Generation of Harbingers"
theme = "blackburn"
author = "ArgosMs"
canonifyurls = true
paginate = 10
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
disableKinds = ["RSS"]

[indexes]
  tag = "tags"
  topic = "topics"
  
[params]
  # Shown in the home page
  subtitle = "with the powerful language of R"
  googleAnalytics = "UA-139013563-1"
  highlightjs = "androidstudio"
  dateFormat = "02 Jan 2006"
  highlightjs_extra_languages = ["r", "yaml"]

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 1
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Posts"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 2
    identifier = "post"
    url = "/post/"
  [[menu.main]]
    name = "Tags"
    pre = "<i class='fa fa-tags fa-fw'></i>"
    weight = 3
    identifier = "tag"
    url = "/tags/"
  [[menu.main]]
    name = "R Labs"
    pre = "<i class='fa fa-binoculars fa-fw'></i>"
    weight = 4
    identifier = "lab"
    url = "/labs/"
  [[menu.main]]
    name = "Leadership"
    pre = "<i class='fa fa-globe fa-fw'></i>"
    weight = 5
    identifier = "leadership"
    url = "/leadership/"
  [[menu.main]]
    name = "Innovation"
    pre = "<i class='fa fa-lightbulb-o fa-fw'></i>"
    weight = 6
    identifier = "innovation"
    url = "/innovation/"
  [[menu.main]]
    name = "Public Policy"
    pre = "<i class='fa fa-university fa-fw'></i>"
    weight = 7
    identifier = "public_policy"
    url = "/public_policy/"
  [[menu.main]]
    name = "Email"
    pre = "<i class='fa fa-paper-plane fa-fw'></i>"
    weight = 8
    url = "/contact/"
  [[menu.main]]
    name = "About"
    pre = "<i class='fa fa-camera-retro fa-fw'></i>"
    weight = 9
    url = "/about/"
    
[social]
    github = "ArgosMs"
    twitter = "@PhantLle"
    instagram = "e.lle.phant"
   
  
  
